// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Register Package auto-generated by `reggen` containing data structure

package isp_wrapper_reg_pkg;

  // Address widths within the block
  parameter int BlockAw = 13;

  ////////////////////////////
  // Typedefs for registers //
  ////////////////////////////

  typedef struct packed {
    struct packed {logic q;} isp;
    struct packed {logic q;} mi;
  } isp_wrapper_reg2hw_intr_state_reg_t;

  typedef struct packed {
    struct packed {logic q;} isp;
    struct packed {logic q;} mi;
  } isp_wrapper_reg2hw_intr_enable_reg_t;

  typedef struct packed {
    struct packed {
      logic q;
      logic qe;
    } isp;
    struct packed {
      logic q;
      logic qe;
    } mi;
  } isp_wrapper_reg2hw_intr_test_reg_t;

  typedef struct packed {
    struct packed {
      logic d;
      logic de;
    } isp;
    struct packed {
      logic d;
      logic de;
    } mi;
  } isp_wrapper_hw2reg_intr_state_reg_t;

  // Register -> HW type
  typedef struct packed {
    isp_wrapper_reg2hw_intr_state_reg_t  intr_state;   // [7:6]
    isp_wrapper_reg2hw_intr_enable_reg_t intr_enable;  // [5:4]
    isp_wrapper_reg2hw_intr_test_reg_t   intr_test;    // [3:0]
  } isp_wrapper_reg2hw_t;

  // HW -> register type
  typedef struct packed {
    isp_wrapper_hw2reg_intr_state_reg_t intr_state;  // [3:0]
  } isp_wrapper_hw2reg_t;

  // Register offsets
  parameter logic [BlockAw-1:0] ISP_WRAPPER_INTR_STATE_OFFSET = 13'h0;
  parameter logic [BlockAw-1:0] ISP_WRAPPER_INTR_ENABLE_OFFSET = 13'h4;
  parameter logic [BlockAw-1:0] ISP_WRAPPER_INTR_TEST_OFFSET = 13'h8;

  // Reset values for hwext registers and their fields
  parameter logic [1:0] ISP_WRAPPER_INTR_TEST_RESVAL = 2'h0;
  parameter logic [0:0] ISP_WRAPPER_INTR_TEST_ISP_RESVAL = 1'h0;
  parameter logic [0:0] ISP_WRAPPER_INTR_TEST_MI_RESVAL = 1'h0;

  // Window parameters
  parameter logic [BlockAw-1:0] ISP_WRAPPER_REG_WINDOW_OFFSET = 13'h1000;
  parameter int unsigned ISP_WRAPPER_REG_WINDOW_SIZE = 'h1000;

  // Register index
  typedef enum int {
    ISP_WRAPPER_INTR_STATE,
    ISP_WRAPPER_INTR_ENABLE,
    ISP_WRAPPER_INTR_TEST
  } isp_wrapper_id_e;

  // Register width information to check illegal writes
  parameter logic [3:0] ISP_WRAPPER_PERMIT[3] = '{
      4'b0001,  // index[0] ISP_WRAPPER_INTR_STATE
      4'b0001,  // index[1] ISP_WRAPPER_INTR_ENABLE
      4'b0001  // index[2] ISP_WRAPPER_INTR_TEST
  };

endpackage
