// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Register Top module auto-generated by `reggen`

`include "prim_assert.sv"

module isp_wrapper_reg_top (
    input clk_i,
    input rst_ni,
    input tlul_pkg::tl_h2d_t tl_i,
    output tlul_pkg::tl_d2h_t tl_o,

    // Output port for window
    output tlul_pkg::tl_h2d_t tl_win_o,
    input  tlul_pkg::tl_d2h_t tl_win_i,

    // To HW
    output isp_wrapper_reg_pkg::isp_wrapper_reg2hw_t reg2hw,  // Write
    input  isp_wrapper_reg_pkg::isp_wrapper_hw2reg_t hw2reg,  // Read

    // Integrity check errors
    output logic intg_err_o,

    // Config
    input devmode_i  // If 1, explicit error return for unmapped register access
);

  import isp_wrapper_reg_pkg::*;

  localparam int AW = 13;
  localparam int DW = 32;
  localparam int DBW = DW / 8;  // Byte Width

  // register signals
  logic           reg_we;
  logic           reg_re;
  logic [ AW-1:0] reg_addr;
  logic [ DW-1:0] reg_wdata;
  logic [DBW-1:0] reg_be;
  logic [ DW-1:0] reg_rdata;
  logic           reg_error;

  logic addrmiss, wr_err;

  logic [DW-1:0] reg_rdata_next;
  logic reg_busy;

  tlul_pkg::tl_h2d_t tl_reg_h2d;
  tlul_pkg::tl_d2h_t tl_reg_d2h;


  // incoming payload check
  logic intg_err;
  tlul_cmd_intg_chk u_chk (
      .tl_i (tl_i),
      .err_o(intg_err)
  );

  // also check for spurious write enables
  logic reg_we_err;
  logic [2:0] reg_we_check;
  prim_reg_we_check #(
      .OneHotWidth(3)
  ) u_prim_reg_we_check (
      .clk_i (clk_i),
      .rst_ni(rst_ni),
      .oh_i  (reg_we_check),
      .en_i  (reg_we && !addrmiss),
      .err_o (reg_we_err)
  );

  logic err_q;
  always_ff @(posedge clk_i or negedge rst_ni) begin
    if (!rst_ni) begin
      err_q <= '0;
    end else if (intg_err || reg_we_err) begin
      err_q <= 1'b1;
    end
  end

  // integrity error output is permanent and should be used for alert generation
  // register errors are transactional
  assign intg_err_o = err_q | intg_err | reg_we_err;

  // outgoing integrity generation
  tlul_pkg::tl_d2h_t tl_o_pre;
  tlul_rsp_intg_gen #(
      .EnableRspIntgGen (1),
      .EnableDataIntgGen(1)
  ) u_rsp_intg_gen (
      .tl_i(tl_o_pre),
      .tl_o(tl_o)
  );

  tlul_pkg::tl_h2d_t tl_socket_h2d[2];
  tlul_pkg::tl_d2h_t tl_socket_d2h[2];

  logic [0:0] reg_steer;

  // socket_1n connection
  assign tl_reg_h2d = tl_socket_h2d[1];
  assign tl_socket_d2h[1] = tl_reg_d2h;

  assign tl_win_o = tl_socket_h2d[0];
  assign tl_socket_d2h[0] = tl_win_i;

  // Create Socket_1n
  tlul_socket_1n #(
      .N           (2),
      .HReqPass    (1'b1),
      .HRspPass    (1'b1),
      .DReqPass    ({2{1'b1}}),
      .DRspPass    ({2{1'b1}}),
      .HReqDepth   (4'h0),
      .HRspDepth   (4'h0),
      .DReqDepth   ({2{4'h0}}),
      .DRspDepth   ({2{4'h0}}),
      .ExplicitErrs(1'b0)
  ) u_socket (
      .clk_i(clk_i),
      .rst_ni(rst_ni),
      .tl_h_i(tl_i),
      .tl_h_o(tl_o_pre),
      .tl_d_o(tl_socket_h2d),
      .tl_d_i(tl_socket_d2h),
      .dev_select_i(reg_steer)
  );

  // Create steering logic
  always_comb begin
    reg_steer = tl_i.a_address[AW-1:0] inside {[4096 : 8191]} ? 1'd0 :
    // Default set to register
    1'd1;

    // Override this in case of an integrity error
    if (intg_err) begin
      reg_steer = 1'd1;
    end
  end

  tlul_adapter_reg #(
      .RegAw(AW),
      .RegDw(DW),
      .EnableDataIntgGen(0)
  ) u_reg_if (
      .clk_i (clk_i),
      .rst_ni(rst_ni),

      .tl_i(tl_reg_h2d),
      .tl_o(tl_reg_d2h),

      .en_ifetch_i (prim_mubi_pkg::MuBi4False),
      .intg_error_o(),

      .we_o   (reg_we),
      .re_o   (reg_re),
      .addr_o (reg_addr),
      .wdata_o(reg_wdata),
      .be_o   (reg_be),
      .busy_i (reg_busy),
      .rdata_i(reg_rdata),
      .error_i(reg_error)
  );

  // cdc oversampling signals

  assign reg_rdata = reg_rdata_next;
  assign reg_error = (devmode_i & addrmiss) | wr_err | intg_err;

  // Define SW related signals
  // Format: <reg>_<field>_{wd|we|qs}
  //        or <reg>_{wd|we|qs} if field == 1 or 0
  logic intr_state_we;
  logic intr_state_isp_qs;
  logic intr_state_isp_wd;
  logic intr_state_mi_qs;
  logic intr_state_mi_wd;
  logic intr_enable_we;
  logic intr_enable_isp_qs;
  logic intr_enable_isp_wd;
  logic intr_enable_mi_qs;
  logic intr_enable_mi_wd;
  logic intr_test_we;
  logic intr_test_isp_wd;
  logic intr_test_mi_wd;

  // Register instances
  // R[intr_state]: V(False)
  //   F[isp]: 0:0
  prim_subreg #(
      .DW      (1),
      .SwAccess(prim_subreg_pkg::SwAccessW1C),
      .RESVAL  (1'h0)
  ) u_intr_state_isp (
      .clk_i (clk_i),
      .rst_ni(rst_ni),

      // from register interface
      .we(intr_state_we),
      .wd(intr_state_isp_wd),

      // from internal hardware
      .de(hw2reg.intr_state.isp.de),
      .d (hw2reg.intr_state.isp.d),

      // to internal hardware
      .qe(),
      .q (reg2hw.intr_state.isp.q),
      .ds(),

      // to register interface (read)
      .qs(intr_state_isp_qs)
  );

  //   F[mi]: 1:1
  prim_subreg #(
      .DW      (1),
      .SwAccess(prim_subreg_pkg::SwAccessW1C),
      .RESVAL  (1'h0)
  ) u_intr_state_mi (
      .clk_i (clk_i),
      .rst_ni(rst_ni),

      // from register interface
      .we(intr_state_we),
      .wd(intr_state_mi_wd),

      // from internal hardware
      .de(hw2reg.intr_state.mi.de),
      .d (hw2reg.intr_state.mi.d),

      // to internal hardware
      .qe(),
      .q (reg2hw.intr_state.mi.q),
      .ds(),

      // to register interface (read)
      .qs(intr_state_mi_qs)
  );


  // R[intr_enable]: V(False)
  //   F[isp]: 0:0
  prim_subreg #(
      .DW      (1),
      .SwAccess(prim_subreg_pkg::SwAccessRW),
      .RESVAL  (1'h0)
  ) u_intr_enable_isp (
      .clk_i (clk_i),
      .rst_ni(rst_ni),

      // from register interface
      .we(intr_enable_we),
      .wd(intr_enable_isp_wd),

      // from internal hardware
      .de(1'b0),
      .d ('0),

      // to internal hardware
      .qe(),
      .q (reg2hw.intr_enable.isp.q),
      .ds(),

      // to register interface (read)
      .qs(intr_enable_isp_qs)
  );

  //   F[mi]: 1:1
  prim_subreg #(
      .DW      (1),
      .SwAccess(prim_subreg_pkg::SwAccessRW),
      .RESVAL  (1'h0)
  ) u_intr_enable_mi (
      .clk_i (clk_i),
      .rst_ni(rst_ni),

      // from register interface
      .we(intr_enable_we),
      .wd(intr_enable_mi_wd),

      // from internal hardware
      .de(1'b0),
      .d ('0),

      // to internal hardware
      .qe(),
      .q (reg2hw.intr_enable.mi.q),
      .ds(),

      // to register interface (read)
      .qs(intr_enable_mi_qs)
  );


  // R[intr_test]: V(True)
  logic intr_test_qe;
  logic [1:0] intr_test_flds_we;
  assign intr_test_qe = &intr_test_flds_we;
  //   F[isp]: 0:0
  prim_subreg_ext #(
      .DW(1)
  ) u_intr_test_isp (
      .re (1'b0),
      .we (intr_test_we),
      .wd (intr_test_isp_wd),
      .d  ('0),
      .qre(),
      .qe (intr_test_flds_we[0]),
      .q  (reg2hw.intr_test.isp.q),
      .ds (),
      .qs ()
  );
  assign reg2hw.intr_test.isp.qe = intr_test_qe;

  //   F[mi]: 1:1
  prim_subreg_ext #(
      .DW(1)
  ) u_intr_test_mi (
      .re (1'b0),
      .we (intr_test_we),
      .wd (intr_test_mi_wd),
      .d  ('0),
      .qre(),
      .qe (intr_test_flds_we[1]),
      .q  (reg2hw.intr_test.mi.q),
      .ds (),
      .qs ()
  );
  assign reg2hw.intr_test.mi.qe = intr_test_qe;



  logic [2:0] addr_hit;
  always_comb begin
    addr_hit = '0;
    addr_hit[0] = (reg_addr == ISP_WRAPPER_INTR_STATE_OFFSET);
    addr_hit[1] = (reg_addr == ISP_WRAPPER_INTR_ENABLE_OFFSET);
    addr_hit[2] = (reg_addr == ISP_WRAPPER_INTR_TEST_OFFSET);
  end

  assign addrmiss = (reg_re || reg_we) ? ~|addr_hit : 1'b0;

  // Check sub-word write is permitted
  always_comb begin
    wr_err = (reg_we &
              ((addr_hit[0] & (|(ISP_WRAPPER_PERMIT[0] & ~reg_be))) |
               (addr_hit[1] & (|(ISP_WRAPPER_PERMIT[1] & ~reg_be))) |
               (addr_hit[2] & (|(ISP_WRAPPER_PERMIT[2] & ~reg_be)))));
  end

  // Generate write-enables
  assign intr_state_we = addr_hit[0] & reg_we & !reg_error;

  assign intr_state_isp_wd = reg_wdata[0];

  assign intr_state_mi_wd = reg_wdata[1];
  assign intr_enable_we = addr_hit[1] & reg_we & !reg_error;

  assign intr_enable_isp_wd = reg_wdata[0];

  assign intr_enable_mi_wd = reg_wdata[1];
  assign intr_test_we = addr_hit[2] & reg_we & !reg_error;

  assign intr_test_isp_wd = reg_wdata[0];

  assign intr_test_mi_wd = reg_wdata[1];

  // Assign write-enables to checker logic vector.
  always_comb begin
    reg_we_check = '0;
    reg_we_check[0] = intr_state_we;
    reg_we_check[1] = intr_enable_we;
    reg_we_check[2] = intr_test_we;
  end

  // Read data return
  always_comb begin
    reg_rdata_next = '0;
    unique case (1'b1)
      addr_hit[0]: begin
        reg_rdata_next[0] = intr_state_isp_qs;
        reg_rdata_next[1] = intr_state_mi_qs;
      end

      addr_hit[1]: begin
        reg_rdata_next[0] = intr_enable_isp_qs;
        reg_rdata_next[1] = intr_enable_mi_qs;
      end

      addr_hit[2]: begin
        reg_rdata_next[0] = '0;
        reg_rdata_next[1] = '0;
      end

      default: begin
        reg_rdata_next = '1;
      end
    endcase
  end

  // shadow busy
  logic shadow_busy;
  assign shadow_busy = 1'b0;

  // register busy
  assign reg_busy = shadow_busy;

  // Unused signal tieoff

  // wdata / byte enable are not always fully used
  // add a blanket unused statement to handle lint waivers
  logic unused_wdata;
  logic unused_be;
  assign unused_wdata = ^reg_wdata;
  assign unused_be = ^reg_be;

  // Assertions for Register Interface
  `ASSERT_PULSE(wePulse, reg_we, clk_i, !rst_ni)
  `ASSERT_PULSE(rePulse, reg_re, clk_i, !rst_ni)

  `ASSERT(reAfterRv, $rose(reg_re || reg_we) |=> tl_o_pre.d_valid, clk_i, !rst_ni)

  `ASSERT(en2addrHit, (reg_we || reg_re) |-> $onehot0(addr_hit), clk_i, !rst_ni)

  // this is formulated as an assumption such that the FPV testbenches do disprove this
  // property by mistake
  //`ASSUME(reqParity, tl_reg_h2d.a_valid |-> tl_reg_h2d.a_user.chk_en == tlul_pkg::CheckDis)

endmodule
