// Copyright 2025 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

module coralnpu_soc
    #(parameter MemInitFile = "",
      parameter int ClockFrequencyMhz = 80)
    (input clk_i,
     input rst_ni,
     input spi_clk_i,
     input spi_csb_i,
     input spi_mosi_i,
     output logic spi_miso_o,
     output logic spim_sclk_o,
     output logic spim_csb_o,
     output logic spim_mosi_o,
     input spim_miso_i,
     input spim_clk_i,
     input [31:0] boot_addr_i,  // PC reset value (0x0 for ITCM, 0x10000000 for ROM)
     output [7:0] gpio_o,
     output [7:0] gpio_en_o,
     input [7:0] gpio_i,
     input prim_mubi_pkg::mubi4_t scanmode_i,
     input top_pkg::uart_sideband_i_t[1 : 0] uart_sideband_i,
     output top_pkg::uart_sideband_o_t[1 : 0] uart_sideband_o,
     input scl_i,
     output logic scl_o,
     output logic scl_en_o,
     input sda_i,
     output logic sda_o,
     output logic sda_en_o,
     output logic io_halted,
     output logic io_fault,
     input ddr_clk_i,
     input ddr_rst,
     output        io_ddr_ctrl_axi_aw_valid,
     input         io_ddr_ctrl_axi_aw_ready,
     output [31:0] io_ddr_ctrl_axi_aw_bits_addr,
     output [2:0]  io_ddr_ctrl_axi_aw_bits_prot,
     output [5:0]  io_ddr_ctrl_axi_aw_bits_id,
     output [7:0]  io_ddr_ctrl_axi_aw_bits_len,
     output [2:0]  io_ddr_ctrl_axi_aw_bits_size,
     output [1:0]  io_ddr_ctrl_axi_aw_bits_burst,
     output        io_ddr_ctrl_axi_aw_bits_lock,
     output [3:0]  io_ddr_ctrl_axi_aw_bits_cache,
                   io_ddr_ctrl_axi_aw_bits_qos,
                   io_ddr_ctrl_axi_aw_bits_region,
     output        io_ddr_ctrl_axi_w_valid,
     input         io_ddr_ctrl_axi_w_ready,
     output [31:0] io_ddr_ctrl_axi_w_bits_data,
     output        io_ddr_ctrl_axi_w_bits_last,
     output [3:0]  io_ddr_ctrl_axi_w_bits_strb,
     input         io_ddr_ctrl_axi_b_valid,
     output        io_ddr_ctrl_axi_b_ready,
     input  [5:0]  io_ddr_ctrl_axi_b_bits_id,
     input  [1:0]  io_ddr_ctrl_axi_b_bits_resp,
     output        io_ddr_ctrl_axi_ar_valid,
     input         io_ddr_ctrl_axi_ar_ready,
     output [31:0] io_ddr_ctrl_axi_ar_bits_addr,
     output [2:0]  io_ddr_ctrl_axi_ar_bits_prot,
     output [5:0]  io_ddr_ctrl_axi_ar_bits_id,
     output [7:0]  io_ddr_ctrl_axi_ar_bits_len,
     output [2:0]  io_ddr_ctrl_axi_ar_bits_size,
     output [1:0]  io_ddr_ctrl_axi_ar_bits_burst,
     output        io_ddr_ctrl_axi_ar_bits_lock,
     output [3:0]  io_ddr_ctrl_axi_ar_bits_cache,
                   io_ddr_ctrl_axi_ar_bits_qos,
                   io_ddr_ctrl_axi_ar_bits_region,
     input         io_ddr_ctrl_axi_r_valid,
     output        io_ddr_ctrl_axi_r_ready,
     input  [31:0] io_ddr_ctrl_axi_r_bits_data,
     input  [5:0]  io_ddr_ctrl_axi_r_bits_id,
     input  [1:0]  io_ddr_ctrl_axi_r_bits_resp,
     input         io_ddr_ctrl_axi_r_bits_last,
     output        io_ddr_mem_axi_aw_valid,
     input         io_ddr_mem_axi_aw_ready,
     output [31:0] io_ddr_mem_axi_aw_bits_addr,
     output [2:0]  io_ddr_mem_axi_aw_bits_prot,
     output [0:0]  io_ddr_mem_axi_aw_bits_id,
     output [7:0]  io_ddr_mem_axi_aw_bits_len,
     output [2:0]  io_ddr_mem_axi_aw_bits_size,
     output [1:0]  io_ddr_mem_axi_aw_bits_burst,
     output        io_ddr_mem_axi_aw_bits_lock,
     output [3:0]  io_ddr_mem_axi_aw_bits_cache,
                   io_ddr_mem_axi_aw_bits_qos,
                   io_ddr_mem_axi_aw_bits_region,
     output        io_ddr_mem_axi_w_valid,
     input         io_ddr_mem_axi_w_ready,
     output [255:0] io_ddr_mem_axi_w_bits_data,
     output        io_ddr_mem_axi_w_bits_last,
     output [31:0]  io_ddr_mem_axi_w_bits_strb,
     input         io_ddr_mem_axi_b_valid,
     output        io_ddr_mem_axi_b_ready,
     input  [0:0]  io_ddr_mem_axi_b_bits_id,
     input  [1:0]  io_ddr_mem_axi_b_bits_resp,
     output        io_ddr_mem_axi_ar_valid,
     input         io_ddr_mem_axi_ar_ready,
     output [31:0] io_ddr_mem_axi_ar_bits_addr,
     output [2:0]  io_ddr_mem_axi_ar_bits_prot,
     output [0:0]  io_ddr_mem_axi_ar_bits_id,
     output [7:0]  io_ddr_mem_axi_ar_bits_len,
     output [2:0]  io_ddr_mem_axi_ar_bits_size,
     output [1:0]  io_ddr_mem_axi_ar_bits_burst,
     output        io_ddr_mem_axi_ar_bits_lock,
     output [3:0]  io_ddr_mem_axi_ar_bits_cache,
                   io_ddr_mem_axi_ar_bits_qos,
                   io_ddr_mem_axi_ar_bits_region,
     input         io_ddr_mem_axi_r_valid,
     output        io_ddr_mem_axi_r_ready,
     input  [255:0] io_ddr_mem_axi_r_bits_data,
     input  [0:0]  io_ddr_mem_axi_r_bits_id,
     input  [1:0]  io_ddr_mem_axi_r_bits_resp,
     input         io_ddr_mem_axi_r_bits_last,
     // RV-DM request
     input io_dm_req_valid,
     input [31:0] io_dm_req_bits_address,
     input [31:0] io_dm_req_bits_data,
     input [1:0] io_dm_req_bits_op,
     output io_dm_req_ready,
     // RV-DM response
     input io_dm_rsp_ready,
     output io_dm_rsp_valid,
     output [31:0] io_dm_rsp_bits_data,
     output [1:0] io_dm_rsp_bits_op
     );

  import tlul_pkg::*;
  import top_pkg::*;

  coralnpu_tlul_pkg_128::tl_h2d_t tl_coralnpu_core_i;
  coralnpu_tlul_pkg_128::tl_d2h_t tl_coralnpu_core_o;
  coralnpu_tlul_pkg_128::tl_h2d_t tl_coralnpu_device_o;
  coralnpu_tlul_pkg_128::tl_d2h_t tl_coralnpu_device_i;

  coralnpu_tlul_pkg_32::tl_h2d_t tl_rom_o_32;
  coralnpu_tlul_pkg_32::tl_d2h_t tl_rom_i_32;

  tl_h2d_t tl_sram_o;
  tl_d2h_t tl_sram_i;

  tl_h2d_t tl_uart0_o;
  tl_d2h_t tl_uart0_i;

  tl_h2d_t tl_uart1_o;
  tl_d2h_t tl_uart1_i;

  coralnpu_tlul_pkg_32::tl_h2d_t tl_i2c_h2d;
  coralnpu_tlul_pkg_32::tl_d2h_t tl_i2c_d2h;

  i2c_master_top i_i2c_master (
    .clk_i(clk_i),
    .rst_ni(rst_ni),
    .tl_i(tl_i2c_h2d),
    .tl_o(tl_i2c_d2h),
    .scl_i(scl_i),
    .scl_o(scl_o),
    .scl_en_o(scl_en_o),
    .sda_i(sda_i),
    .sda_o(sda_o),
    .sda_en_o(sda_en_o)
  );

  uart i_uart0(.clk_i(clk_i),
               .rst_ni(rst_ni),
               .tl_i(tl_uart0_o),
               .tl_o(tl_uart0_i),
               .alert_rx_i(1'b0),
               .alert_tx_o(),
               .racl_policies_i(1'b0),
               .racl_error_o(),
               .cio_rx_i(uart_sideband_i[0].cio_rx),
               .cio_tx_o(uart_sideband_o[0].cio_tx),
               .cio_tx_en_o(uart_sideband_o[0].cio_tx_en),
               .intr_tx_watermark_o(uart_sideband_o[0].intr_tx_watermark),
               .intr_tx_empty_o(uart_sideband_o[0].intr_tx_empty),
               .intr_rx_watermark_o(uart_sideband_o[0].intr_rx_watermark),
               .intr_tx_done_o(uart_sideband_o[0].intr_tx_done),
               .intr_rx_overflow_o(uart_sideband_o[0].intr_rx_overflow),
               .intr_rx_frame_err_o(uart_sideband_o[0].intr_rx_frame_err),
               .intr_rx_break_err_o(uart_sideband_o[0].intr_rx_break_err),
               .intr_rx_timeout_o(uart_sideband_o[0].intr_rx_timeout),
               .intr_rx_parity_err_o(uart_sideband_o[0].intr_rx_parity_err),
               .lsio_trigger_o(uart_sideband_o[0].lsio_trigger));

  uart i_uart1(.clk_i(clk_i),
               .rst_ni(rst_ni),
               .tl_i(tl_uart1_o),
               .tl_o(tl_uart1_i),
               .alert_rx_i(1'b0),
               .alert_tx_o(),
               .racl_policies_i(1'b0),
               .racl_error_o(),
               .cio_rx_i(uart_sideband_i[1].cio_rx),
               .cio_tx_o(uart_sideband_o[1].cio_tx),
               .cio_tx_en_o(uart_sideband_o[1].cio_tx_en),
               .intr_tx_watermark_o(uart_sideband_o[1].intr_tx_watermark),
               .intr_tx_empty_o(uart_sideband_o[1].intr_tx_empty),
               .intr_rx_watermark_o(uart_sideband_o[1].intr_rx_watermark),
               .intr_tx_done_o(uart_sideband_o[1].intr_tx_done),
               .intr_rx_overflow_o(uart_sideband_o[1].intr_rx_overflow),
               .intr_rx_frame_err_o(uart_sideband_o[1].intr_rx_frame_err),
               .intr_rx_break_err_o(uart_sideband_o[1].intr_rx_break_err),
               .intr_rx_timeout_o(uart_sideband_o[1].intr_rx_timeout),
               .intr_rx_parity_err_o(uart_sideband_o[1].intr_rx_parity_err),
               .lsio_trigger_o(uart_sideband_o[1].lsio_trigger));

  logic rom_req;
  logic [10 : 0] rom_addr;
  logic [31 : 0] rom_rdata;
  logic rom_we;
  logic [31 : 0] rom_wdata;
  logic [3 : 0] rom_wmask;
  logic rom_rvalid;

  tlul_adapter_sram #(.SramAw(11),
                      .SramDw(32),
                      .ErrOnWrite(1),
                      .CmdIntgCheck(1'b1),
                      .EnableRspIntgGen(1'b1),
                      .EnableDataIntgGen(1'b1))
      i_rom_adapter(.clk_i(clk_i),
                    .rst_ni(rst_ni),
                    .tl_i(tl_rom_o_32),
                    .tl_o(tl_rom_i_32),
                    .req_o(rom_req),
                    .we_o(rom_we),
                    .addr_o(rom_addr),
                    .wdata_o(rom_wdata),
                    .wmask_o(rom_wmask),
                    .rdata_i(rom_rdata),
                    .gnt_i(1'b1),
                    .rvalid_i(rom_rvalid),
                    .en_ifetch_i(prim_mubi_pkg::MuBi4True),
                    .req_type_o(),
                    .intg_error_o(),
                    .user_rsvd_o(),
                    .rerror_i(2'b0),
                    .compound_txn_in_progress_o(),
                    .readback_en_i(4'b0),
                    .readback_error_o(),
                    .wr_collision_i(1'b0),
                    .write_pending_i(1'b0));

  prim_rom_adv #(.Width(32),
                 .Depth(2048),
                 .MemInitFile(MemInitFile))
      i_rom(.clk_i(clk_i),
            .rst_ni(rst_ni),
            .req_i(rom_req),
            .addr_i(rom_addr),
            .rvalid_o(rom_rvalid),
            .rdata_o(rom_rdata),
            .cfg_i('0));

  logic sram_req;
  logic sram_we;
  logic [19 : 0] sram_addr;
  logic [31 : 0] sram_wdata;
  logic [31 : 0] sram_wmask_bits;
  logic [31 : 0] sram_rdata;
  logic sram_rvalid;

  tlul_adapter_sram #(.SramAw(20),
                      .SramDw(32),
                      .CmdIntgCheck(1'b1),
                      .EnableRspIntgGen(1'b1),
                      .EnableDataIntgGen(1'b1))
      i_sram_adapter(.clk_i(clk_i),
                     .rst_ni(rst_ni),
                     .tl_i(tl_sram_o),
                     .tl_o(tl_sram_i),
                     .req_o(sram_req),
                     .we_o(sram_we),
                     .addr_o(sram_addr),
                     .wdata_o(sram_wdata),
                     .wmask_o(sram_wmask_bits),
                     .rdata_i(sram_rdata),
                     .gnt_i(1'b1),
                     .rvalid_i(sram_rvalid),
                     .en_ifetch_i(prim_mubi_pkg::MuBi4True),
                     .req_type_o(),
                     .intg_error_o(),
                     .user_rsvd_o(),
                     .rerror_i(2'b0),
                     .compound_txn_in_progress_o(),
                     .readback_en_i(4'b0),
                     .readback_error_o(),
                     .wr_collision_i(1'b0),
                     .write_pending_i(1'b0));

  Sram #(.Width(32),
         .Depth(1048576))
      i_sram(.clk_i(clk_i),
             .req_i(sram_req),
             .we_i(sram_we),
             .addr_i(sram_addr),
             .wdata_i(sram_wdata),
             .wmask_i({sram_wmask_bits[24], sram_wmask_bits[16], sram_wmask_bits[8], sram_wmask_bits[0]}),
             .rdata_o(sram_rdata),
             .rvalid_o(sram_rvalid));

  CoralNPUChiselSubsystem i_chisel_subsystem (
    .io_clk_i(clk_i),
    .io_rst_ni(rst_ni),

    // External Device Port 0: rom
    .io_external_devices_rom_a_valid(tl_rom_o_32.a_valid),
    .io_external_devices_rom_a_bits_opcode(tl_rom_o_32.a_opcode),
    .io_external_devices_rom_a_bits_param(tl_rom_o_32.a_param),
    .io_external_devices_rom_a_bits_size(tl_rom_o_32.a_size),
    .io_external_devices_rom_a_bits_source(tl_rom_o_32.a_source),
    .io_external_devices_rom_a_bits_address(tl_rom_o_32.a_address),
    .io_external_devices_rom_a_bits_mask(tl_rom_o_32.a_mask),
    .io_external_devices_rom_a_bits_data(tl_rom_o_32.a_data),
    .io_external_devices_rom_a_bits_user_rsvd(tl_rom_o_32.a_user.rsvd),
    .io_external_devices_rom_a_bits_user_instr_type(tl_rom_o_32.a_user.instr_type),
    .io_external_devices_rom_a_bits_user_cmd_intg(tl_rom_o_32.a_user.cmd_intg),
    .io_external_devices_rom_a_bits_user_data_intg(tl_rom_o_32.a_user.data_intg),
    .io_external_devices_rom_d_ready(tl_rom_o_32.d_ready),
    .io_external_devices_rom_a_ready(tl_rom_i_32.a_ready),
    .io_external_devices_rom_d_valid(tl_rom_i_32.d_valid),
    .io_external_devices_rom_d_bits_opcode(tl_rom_i_32.d_opcode),
    .io_external_devices_rom_d_bits_param(tl_rom_i_32.d_param),
    .io_external_devices_rom_d_bits_size(tl_rom_i_32.d_size),
    .io_external_devices_rom_d_bits_source(tl_rom_i_32.d_source),
    .io_external_devices_rom_d_bits_sink(tl_rom_i_32.d_sink),
    .io_external_devices_rom_d_bits_data(tl_rom_i_32.d_data),
    .io_external_devices_rom_d_bits_error(tl_rom_i_32.d_error),
    .io_external_devices_rom_d_bits_user_rsp_intg(tl_rom_i_32.d_user.rsp_intg),
    .io_external_devices_rom_d_bits_user_data_intg(tl_rom_i_32.d_user.data_intg),

    // External Device Port 1: sram
    .io_external_devices_sram_a_valid(tl_sram_o.a_valid),
    .io_external_devices_sram_a_bits_opcode(tl_sram_o.a_opcode),
    .io_external_devices_sram_a_bits_param(tl_sram_o.a_param),
    .io_external_devices_sram_a_bits_size(tl_sram_o.a_size),
    .io_external_devices_sram_a_bits_source(tl_sram_o.a_source),
    .io_external_devices_sram_a_bits_address(tl_sram_o.a_address),
    .io_external_devices_sram_a_bits_mask(tl_sram_o.a_mask),
    .io_external_devices_sram_a_bits_data(tl_sram_o.a_data),
    .io_external_devices_sram_a_bits_user_rsvd(tl_sram_o.a_user.rsvd),
    .io_external_devices_sram_a_bits_user_instr_type(tl_sram_o.a_user.instr_type),
    .io_external_devices_sram_a_bits_user_cmd_intg(tl_sram_o.a_user.cmd_intg),
    .io_external_devices_sram_a_bits_user_data_intg(tl_sram_o.a_user.data_intg),
    .io_external_devices_sram_d_ready(tl_sram_o.d_ready),
    .io_external_devices_sram_a_ready(tl_sram_i.a_ready),
    .io_external_devices_sram_d_valid(tl_sram_i.d_valid),
    .io_external_devices_sram_d_bits_opcode(tl_sram_i.d_opcode),
    .io_external_devices_sram_d_bits_param(tl_sram_i.d_param),
    .io_external_devices_sram_d_bits_size(tl_sram_i.d_size),
    .io_external_devices_sram_d_bits_source(tl_sram_i.d_source),
    .io_external_devices_sram_d_bits_sink(tl_sram_i.d_sink),
    .io_external_devices_sram_d_bits_data(tl_sram_i.d_data),
    .io_external_devices_sram_d_bits_error(tl_sram_i.d_error),
    .io_external_devices_sram_d_bits_user_rsp_intg(tl_sram_i.d_user.rsp_intg),
    .io_external_devices_sram_d_bits_user_data_intg(tl_sram_i.d_user.data_intg),

    // External Device Port 2: uart0
    .io_external_devices_uart0_a_valid(tl_uart0_o.a_valid),
    .io_external_devices_uart0_a_bits_opcode(tl_uart0_o.a_opcode),
    .io_external_devices_uart0_a_bits_param(tl_uart0_o.a_param),
    .io_external_devices_uart0_a_bits_size(tl_uart0_o.a_size),
    .io_external_devices_uart0_a_bits_source(tl_uart0_o.a_source),
    .io_external_devices_uart0_a_bits_address(tl_uart0_o.a_address),
    .io_external_devices_uart0_a_bits_mask(tl_uart0_o.a_mask),
    .io_external_devices_uart0_a_bits_data(tl_uart0_o.a_data),
    .io_external_devices_uart0_a_bits_user_rsvd(tl_uart0_o.a_user.rsvd),
    .io_external_devices_uart0_a_bits_user_instr_type(tl_uart0_o.a_user.instr_type),
    .io_external_devices_uart0_a_bits_user_cmd_intg(tl_uart0_o.a_user.cmd_intg),
    .io_external_devices_uart0_a_bits_user_data_intg(tl_uart0_o.a_user.data_intg),
    .io_external_devices_uart0_d_ready(tl_uart0_o.d_ready),
    .io_external_devices_uart0_a_ready(tl_uart0_i.a_ready),
    .io_external_devices_uart0_d_valid(tl_uart0_i.d_valid),
    .io_external_devices_uart0_d_bits_opcode(tl_uart0_i.d_opcode),
    .io_external_devices_uart0_d_bits_param(tl_uart0_i.d_param),
    .io_external_devices_uart0_d_bits_size(tl_uart0_i.d_size),
    .io_external_devices_uart0_d_bits_source(tl_uart0_i.d_source),
    .io_external_devices_uart0_d_bits_sink(tl_uart0_i.d_sink),
    .io_external_devices_uart0_d_bits_data(tl_uart0_i.d_data),
    .io_external_devices_uart0_d_bits_error(tl_uart0_i.d_error),
    .io_external_devices_uart0_d_bits_user_rsp_intg(tl_uart0_i.d_user.rsp_intg),
    .io_external_devices_uart0_d_bits_user_data_intg(tl_uart0_i.d_user.data_intg),

    // External Device Port 3: uart1
    .io_external_devices_uart1_a_valid(tl_uart1_o.a_valid),
    .io_external_devices_uart1_a_bits_opcode(tl_uart1_o.a_opcode),
    .io_external_devices_uart1_a_bits_param(tl_uart1_o.a_param),
    .io_external_devices_uart1_a_bits_size(tl_uart1_o.a_size),
    .io_external_devices_uart1_a_bits_source(tl_uart1_o.a_source),
    .io_external_devices_uart1_a_bits_address(tl_uart1_o.a_address),
    .io_external_devices_uart1_a_bits_mask(tl_uart1_o.a_mask),
    .io_external_devices_uart1_a_bits_data(tl_uart1_o.a_data),
    .io_external_devices_uart1_a_bits_user_rsvd(tl_uart1_o.a_user.rsvd),
    .io_external_devices_uart1_a_bits_user_instr_type(tl_uart1_o.a_user.instr_type),
    .io_external_devices_uart1_a_bits_user_cmd_intg(tl_uart1_o.a_user.cmd_intg),
    .io_external_devices_uart1_a_bits_user_data_intg(tl_uart1_o.a_user.data_intg),
    .io_external_devices_uart1_d_ready(tl_uart1_o.d_ready),
    .io_external_devices_uart1_a_ready(tl_uart1_i.a_ready),
    .io_external_devices_uart1_d_valid(tl_uart1_i.d_valid),
    .io_external_devices_uart1_d_bits_opcode(tl_uart1_i.d_opcode),
    .io_external_devices_uart1_d_bits_param(tl_uart1_i.d_param),
    .io_external_devices_uart1_d_bits_size(tl_uart1_i.d_size),
    .io_external_devices_uart1_d_bits_source(tl_uart1_i.d_source),
    .io_external_devices_uart1_d_bits_sink(tl_uart1_i.d_sink),
    .io_external_devices_uart1_d_bits_data(tl_uart1_i.d_data),
    .io_external_devices_uart1_d_bits_error(tl_uart1_i.d_error),
    .io_external_devices_uart1_d_bits_user_rsp_intg(tl_uart1_i.d_user.rsp_intg),
    .io_external_devices_uart1_d_bits_user_data_intg(tl_uart1_i.d_user.data_intg),

    // External Device Port 4: i2c_master
    .io_external_devices_i2c_master_a_valid(tl_i2c_h2d.a_valid),
    .io_external_devices_i2c_master_a_bits_opcode(tl_i2c_h2d.a_opcode),
    .io_external_devices_i2c_master_a_bits_param(tl_i2c_h2d.a_param),
    .io_external_devices_i2c_master_a_bits_size(tl_i2c_h2d.a_size),
    .io_external_devices_i2c_master_a_bits_source(tl_i2c_h2d.a_source),
    .io_external_devices_i2c_master_a_bits_address(tl_i2c_h2d.a_address),
    .io_external_devices_i2c_master_a_bits_mask(tl_i2c_h2d.a_mask),
    .io_external_devices_i2c_master_a_bits_data(tl_i2c_h2d.a_data),
    .io_external_devices_i2c_master_a_bits_user_rsvd(tl_i2c_h2d.a_user.rsvd),
    .io_external_devices_i2c_master_a_bits_user_instr_type(tl_i2c_h2d.a_user.instr_type),
    .io_external_devices_i2c_master_a_bits_user_cmd_intg(tl_i2c_h2d.a_user.cmd_intg),
    .io_external_devices_i2c_master_a_bits_user_data_intg(tl_i2c_h2d.a_user.data_intg),
    .io_external_devices_i2c_master_d_ready(tl_i2c_h2d.d_ready),
    .io_external_devices_i2c_master_a_ready(tl_i2c_d2h.a_ready),
    .io_external_devices_i2c_master_d_valid(tl_i2c_d2h.d_valid),
    .io_external_devices_i2c_master_d_bits_opcode(tl_i2c_d2h.d_opcode),
    .io_external_devices_i2c_master_d_bits_param(tl_i2c_d2h.d_param),
    .io_external_devices_i2c_master_d_bits_size(tl_i2c_d2h.d_size),
    .io_external_devices_i2c_master_d_bits_source(tl_i2c_d2h.d_source),
    .io_external_devices_i2c_master_d_bits_sink(tl_i2c_d2h.d_sink),
    .io_external_devices_i2c_master_d_bits_data(tl_i2c_d2h.d_data),
    .io_external_devices_i2c_master_d_bits_error(tl_i2c_d2h.d_error),
    .io_external_devices_i2c_master_d_bits_user_rsp_intg(tl_i2c_d2h.d_user.rsp_intg),
    .io_external_devices_i2c_master_d_bits_user_data_intg(tl_i2c_d2h.d_user.data_intg),

    // Peripheral Ports
    .io_external_ports_halted(io_halted),      // halted
    .io_external_ports_fault(io_fault),       // fault
    .io_external_ports_wfi(),               // wfi (unused)
    .io_external_ports_irq(1'b0),           // irq (tied off)
    .io_external_ports_te(1'b0),           // te (tied off)
    .io_external_ports_boot_addr(boot_addr_i),
    .io_external_ports_dm_req_valid(io_dm_req_valid),
    .io_external_ports_dm_req_ready(io_dm_req_ready),
    .io_external_ports_dm_req_bits_address(io_dm_req_bits_address),
    .io_external_ports_dm_req_bits_data(io_dm_req_bits_data),
    .io_external_ports_dm_req_bits_op(io_dm_req_bits_op),
    .io_external_ports_dm_rsp_valid(io_dm_rsp_valid),
    .io_external_ports_dm_rsp_ready(io_dm_rsp_ready),
    .io_external_ports_dm_rsp_bits_data(io_dm_rsp_bits_data),
    .io_external_ports_dm_rsp_bits_op(io_dm_rsp_bits_op),
    .io_external_ports_spi_clk(spi_clk_i),      // spi_clk
    .io_external_ports_spi_csb(spi_csb_i),      // spi_csb
    .io_external_ports_spi_mosi(spi_mosi_i),     // spi_mosi
    .io_external_ports_spi_miso(spi_miso_o),     // spi_miso
    .io_external_ports_spim_sclk(spim_sclk_o),
    .io_external_ports_spim_csb(spim_csb_o),
    .io_external_ports_spim_mosi(spim_mosi_o),
    .io_external_ports_spim_miso(spim_miso_i),
    .io_external_ports_spim_clk_i(spim_clk_i),
    .io_external_ports_gpio_o(gpio_o),
    .io_external_ports_gpio_en_o(gpio_en_o),
    .io_external_ports_gpio_i(gpio_i),

    .io_async_ports_devices_ddr_clock(ddr_clk_i),
    .io_async_ports_devices_ddr_reset(ddr_rst),

    .io_ddr_ctrl_axi_write_addr_valid(io_ddr_ctrl_axi_aw_valid),
    .io_ddr_ctrl_axi_write_addr_ready(io_ddr_ctrl_axi_aw_ready),
    .io_ddr_ctrl_axi_write_addr_bits_addr(io_ddr_ctrl_axi_aw_bits_addr),
    .io_ddr_ctrl_axi_write_addr_bits_prot(io_ddr_ctrl_axi_aw_bits_prot),
    .io_ddr_ctrl_axi_write_addr_bits_id(io_ddr_ctrl_axi_aw_bits_id),
    .io_ddr_ctrl_axi_write_addr_bits_len(io_ddr_ctrl_axi_aw_bits_len),
    .io_ddr_ctrl_axi_write_addr_bits_size(io_ddr_ctrl_axi_aw_bits_size),
    .io_ddr_ctrl_axi_write_addr_bits_burst(io_ddr_ctrl_axi_aw_bits_burst),
    .io_ddr_ctrl_axi_write_addr_bits_lock(io_ddr_ctrl_axi_aw_bits_lock),
    .io_ddr_ctrl_axi_write_addr_bits_cache(io_ddr_ctrl_axi_aw_bits_cache),
    .io_ddr_ctrl_axi_write_addr_bits_qos(io_ddr_ctrl_axi_aw_bits_qos),
    .io_ddr_ctrl_axi_write_addr_bits_region(io_ddr_ctrl_axi_aw_bits_region),
    .io_ddr_ctrl_axi_write_data_valid(io_ddr_ctrl_axi_w_valid),
    .io_ddr_ctrl_axi_write_data_ready(io_ddr_ctrl_axi_w_ready),
    .io_ddr_ctrl_axi_write_data_bits_data(io_ddr_ctrl_axi_w_bits_data),
    .io_ddr_ctrl_axi_write_data_bits_last(io_ddr_ctrl_axi_w_bits_last),
    .io_ddr_ctrl_axi_write_data_bits_strb(io_ddr_ctrl_axi_w_bits_strb),
    .io_ddr_ctrl_axi_write_resp_valid(io_ddr_ctrl_axi_b_valid),
    .io_ddr_ctrl_axi_write_resp_ready(io_ddr_ctrl_axi_b_ready),
    .io_ddr_ctrl_axi_write_resp_bits_id(io_ddr_ctrl_axi_b_bits_id),
    .io_ddr_ctrl_axi_write_resp_bits_resp(io_ddr_ctrl_axi_b_bits_resp),
    .io_ddr_ctrl_axi_read_addr_valid(io_ddr_ctrl_axi_ar_valid),
    .io_ddr_ctrl_axi_read_addr_ready(io_ddr_ctrl_axi_ar_ready),
    .io_ddr_ctrl_axi_read_addr_bits_addr(io_ddr_ctrl_axi_ar_bits_addr),
    .io_ddr_ctrl_axi_read_addr_bits_prot(io_ddr_ctrl_axi_ar_bits_prot),
    .io_ddr_ctrl_axi_read_addr_bits_id(io_ddr_ctrl_axi_ar_bits_id),
    .io_ddr_ctrl_axi_read_addr_bits_len(io_ddr_ctrl_axi_ar_bits_len),
    .io_ddr_ctrl_axi_read_addr_bits_size(io_ddr_ctrl_axi_ar_bits_size),
    .io_ddr_ctrl_axi_read_addr_bits_burst(io_ddr_ctrl_axi_ar_bits_burst),
    .io_ddr_ctrl_axi_read_addr_bits_lock(io_ddr_ctrl_axi_ar_bits_lock),
    .io_ddr_ctrl_axi_read_addr_bits_cache(io_ddr_ctrl_axi_ar_bits_cache),
    .io_ddr_ctrl_axi_read_addr_bits_qos(io_ddr_ctrl_axi_ar_bits_qos),
    .io_ddr_ctrl_axi_read_addr_bits_region(io_ddr_ctrl_axi_ar_bits_region),
    .io_ddr_ctrl_axi_read_data_valid(io_ddr_ctrl_axi_r_valid),
    .io_ddr_ctrl_axi_read_data_ready(io_ddr_ctrl_axi_r_ready),
    .io_ddr_ctrl_axi_read_data_bits_data(io_ddr_ctrl_axi_r_bits_data),
    .io_ddr_ctrl_axi_read_data_bits_id(io_ddr_ctrl_axi_r_bits_id),
    .io_ddr_ctrl_axi_read_data_bits_resp(io_ddr_ctrl_axi_r_bits_resp),
    .io_ddr_ctrl_axi_read_data_bits_last(io_ddr_ctrl_axi_r_bits_last),
    .io_ddr_mem_axi_write_addr_valid(io_ddr_mem_axi_aw_valid),
    .io_ddr_mem_axi_write_addr_ready(io_ddr_mem_axi_aw_ready),
    .io_ddr_mem_axi_write_addr_bits_addr(io_ddr_mem_axi_aw_bits_addr),
    .io_ddr_mem_axi_write_addr_bits_prot(io_ddr_mem_axi_aw_bits_prot),
    .io_ddr_mem_axi_write_addr_bits_id(io_ddr_mem_axi_aw_bits_id),
    .io_ddr_mem_axi_write_addr_bits_len(io_ddr_mem_axi_aw_bits_len),
    .io_ddr_mem_axi_write_addr_bits_size(io_ddr_mem_axi_aw_bits_size),
    .io_ddr_mem_axi_write_addr_bits_burst(io_ddr_mem_axi_aw_bits_burst),
    .io_ddr_mem_axi_write_addr_bits_lock(io_ddr_mem_axi_aw_bits_lock),
    .io_ddr_mem_axi_write_addr_bits_cache(io_ddr_mem_axi_aw_bits_cache),
    .io_ddr_mem_axi_write_addr_bits_qos(io_ddr_mem_axi_aw_bits_qos),
    .io_ddr_mem_axi_write_addr_bits_region(io_ddr_mem_axi_aw_bits_region),
    .io_ddr_mem_axi_write_data_valid(io_ddr_mem_axi_w_valid),
    .io_ddr_mem_axi_write_data_ready(io_ddr_mem_axi_w_ready),
    .io_ddr_mem_axi_write_data_bits_data(io_ddr_mem_axi_w_bits_data),
    .io_ddr_mem_axi_write_data_bits_last(io_ddr_mem_axi_w_bits_last),
    .io_ddr_mem_axi_write_data_bits_strb(io_ddr_mem_axi_w_bits_strb),
    .io_ddr_mem_axi_write_resp_valid(io_ddr_mem_axi_b_valid),
    .io_ddr_mem_axi_write_resp_ready(io_ddr_mem_axi_b_ready),
    .io_ddr_mem_axi_write_resp_bits_id(io_ddr_mem_axi_b_bits_id),
    .io_ddr_mem_axi_write_resp_bits_resp(io_ddr_mem_axi_b_bits_resp),
    .io_ddr_mem_axi_read_addr_valid(io_ddr_mem_axi_ar_valid),
    .io_ddr_mem_axi_read_addr_ready(io_ddr_mem_axi_ar_ready),
    .io_ddr_mem_axi_read_addr_bits_addr(io_ddr_mem_axi_ar_bits_addr),
    .io_ddr_mem_axi_read_addr_bits_prot(io_ddr_mem_axi_ar_bits_prot),
    .io_ddr_mem_axi_read_addr_bits_id(io_ddr_mem_axi_ar_bits_id),
    .io_ddr_mem_axi_read_addr_bits_len(io_ddr_mem_axi_ar_bits_len),
    .io_ddr_mem_axi_read_addr_bits_size(io_ddr_mem_axi_ar_bits_size),
    .io_ddr_mem_axi_read_addr_bits_burst(io_ddr_mem_axi_ar_bits_burst),
    .io_ddr_mem_axi_read_addr_bits_lock(io_ddr_mem_axi_ar_bits_lock),
    .io_ddr_mem_axi_read_addr_bits_cache(io_ddr_mem_axi_ar_bits_cache),
    .io_ddr_mem_axi_read_addr_bits_qos(io_ddr_mem_axi_ar_bits_qos),
    .io_ddr_mem_axi_read_addr_bits_region(io_ddr_mem_axi_ar_bits_region),
    .io_ddr_mem_axi_read_data_valid(io_ddr_mem_axi_r_valid),
    .io_ddr_mem_axi_read_data_ready(io_ddr_mem_axi_r_ready),
    .io_ddr_mem_axi_read_data_bits_data(io_ddr_mem_axi_r_bits_data),
    .io_ddr_mem_axi_read_data_bits_id(io_ddr_mem_axi_r_bits_id),
    .io_ddr_mem_axi_read_data_bits_resp(io_ddr_mem_axi_r_bits_resp),
    .io_ddr_mem_axi_read_data_bits_last(io_ddr_mem_axi_r_bits_last)
  );
endmodule
